apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swift-pvc
spec:
  storageClassName: "rclone"
  accessModes:
    - ReadWriteMany
  csi:
    driver: csi-rclone
    volumeHandle: "swift-pv"
    volumeAttributes:
      file-perms: "0777"
      links: "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: swift-pv
spec:
  storageClassName: "rclone"
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: swift-pvc
---
